# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain Python dependencies (Poetry/pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain Dockerfile base images (Root)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  
  # Maintain Dockerfile base images (Services)
  - package-ecosystem: "docker"
    directory: "/netra"
    schedule:
      interval: "weekly"

  # Maintain GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
