services:

  netra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netra-backend
    command: python run.py
    ports:
      - "8000:8000"
    volumes:
      - .:
